language: python
dist: xenial
python:
  3.7
install:
  - pip install -r requirements.txt
before_script:
  - sudo locale-gen cs_CZ
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - pip install -r tests/requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - py.test tests --cov=shromazdeni --cov-report=term-missing
  - flake8 shromazdeni tests
  - black --check .
  - mypy --ignore-missing-imports .
after_success:
  - coveralls
